// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// totalDistance
double totalDistance(NumericVector dist_vec, int nrows, IntegerVector medoids, IntegerVector clustering);
RcppExport SEXP _WOAkMedoids_totalDistance(SEXP dist_vecSEXP, SEXP nrowsSEXP, SEXP medoidsSEXP, SEXP clusteringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dist_vec(dist_vecSEXP);
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type medoids(medoidsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type clustering(clusteringSEXP);
    rcpp_result_gen = Rcpp::wrap(totalDistance(dist_vec, nrows, medoids, clustering));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WOAkMedoids_totalDistance", (DL_FUNC) &_WOAkMedoids_totalDistance, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_WOAkMedoids(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
