# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

totalDistance <- function(dist_vec, nrows, medoids, clustering) {
    .Call('_WOAkMedoids_totalDistance', PACKAGE = 'WOAkMedoids', dist_vec, nrows, medoids, clustering)
}

